### ISSUE TITLE
Email presentation

### ISSUE THREAD

**Issue by leahy268** [SSWConsulting/SSW.Dory#13]
```[tasklist]
### Tasks
- [x] Remove SSW Logo
- [x] Add our usual link to the bottom of the sent email
- [x] Add greeting
- [x] Finish finnessing the layout
```
