### ISSUE TITLE
SharePoint - Create a list for Dory called SSW.Dory on main site

### ISSUE THREAD

**Issue by leahy268** [SSWConsulting/SSW.Dory#17]
```[tasklist]
### Tasks
- [x] Create list called SSW.Dory
- [x] Update flow to use new list name
- [x] Set view to default to My Intranet
```
