### ISSUE TITLE
Investigate SSW.Dory Website

### ISSUE THREAD

**Issue by leahy268** [SSWConsulting/SSW.Dory#21]
Site similar to CodeAuditor that advertises what Dory can do
```[tasklist]
### Tasks
- [x] Double check with Adam what he wants in this
- [x] Contact designers
- [x] Double check with Adam that he's fine with making the repo public for GitHub Pages as it is essentially empty
- [x] Clean up ReadME
```

**Comment by Jord-Gui** [comment]
Done - as per conversation with @adamcogan @leahy268 @tiagov8 @wicksipedia @pierssinclairssw, website will be hosted using GitHub Pages
