### ISSUE TITLE
📝 Documentation - Find or create a rule

### ISSUE THREAD

**Issue by leahy268** [SSWConsulting/SSW.Dory#24]
```[tasklist]
### Tasks
- [ ] Find or Create a rule that matches 'making sure that you aren't blocking anyone'
- [ ] Add to the top of the email
- [ ] Add to the page that contains the SharePoint list
```

**Comment by Tanya-Leahy** [comment]
Dory was created in response to the following rules and the SSW Dory website has been added to each:
URL: https://www.ssw.com.au/rules/no-checked-out-files/
URL: https://ssw.com.au/rules/merge-debt/
