### ISSUE TITLE
♻️ Clean up (productise) Power Automate flow so that it is easy enough for other companies to use it

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#26]
```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Dory/issues/77
- [ ] https://github.com/SSWConsulting/SSW.Dory/issues/106
- [ ] https://github.com/SSWConsulting/SSW.Dory/issues/56
- [ ] https://github.com/SSWConsulting/SSW.Dory/issues/20
- [ ] Figure out how other people can set up/buy SSW Dory as a product
- [ ] Update CTA on SSW Dory website once productised
```

**Comment by Jord-Gui** [comment]
Good point raised by @calumjs - the outstanding task list that SSWDory currently writes to is a SharePoint list, which could be a barrier-of-entry for companies that don't use SharePoint (if we sell this as a product with configurable data sources e.g., only check GitHub). 

Potential solutions:
- Power BI report (consolidated view)
- Separate them out (SharePoint tasks to a SharePoint page, GitHub tasks to a GitHub discussion post with a markdown table of outstanding PRs and tagging the people who they are assigned to)
- Another platform
- Do nothing


![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/b6d8d64b-8639-4d94-8e42-7ae577857436) \
Figure: SharePoint list of outstanding tasks

**Comment by Jord-Gui** [comment]
As per my conversation with @wicksipedia this morning, we have just got access to Azure Marketplace for SSW.Dory enabled this morning. There's a lot of work involved to get it ready as a product e.g., change necessary values into variables. 

Aim is for it to be a published Power App on the marketplace. Could even split it into separate apps that checks for SharePoint and GitHub. 

To start of with, call-to-action can be to send then to the booking site, similar to on SSW website.

**Comment by wicksipedia** [comment]
> As per my conversation with @wicksipedia this morning

we didn't talk this morning

**Comment by Jord-Gui** [comment]
@wicksipedia sorry, wrong tag 😅. Was meant ot be @leahy268
