### ISSUE TITLE
♻️ Changes to SSW.Dory Email Template

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#38]
Small tweaks to the SSW.Dory email template following discussion with @tiagov8 @JackDevAU @bradystroud 

```[tasklist]
### Tasks
- [x] Add more detail to the GitHub email steps on options to take
- [x] Subject emojis look weird, ask for feedback e.g. Tiago
- [x] Add the user's name into the email subject
```

**Comment by tiagov8** [comment]
Hi @Jord-Gui 

My suggestion is to change from:

> From: SSW Dory [SSW]
> Sent: Wednesday, 23 August 2023 8:01 AM
> To: Levi Jackson [SSW] <[LeviJackson@ssw.com.au](mailto:LeviJackson@ssw.com.au)>
> Cc: SSWDoryEmails <[SSWDoryEmails@ssw.com.au](mailto:SSWDoryEmails@ssw.com.au)>
> Subject: SSW.Dory | 🔷 SharePoint files need your attention
>  
> This product is currently in BETA, we are keen for your feedback.
> 
> Hi Levi,
> You currently have the following pages checked out in SharePoint:
> 
> * [https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-09.aspx](https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-09.aspx)
> * [https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-11.aspx](https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-11.aspx)
>
> 1. If you are no longer editing these files, check them in!
> Note: You should check in at least daily, as per rule [SSW.Rules | Do you confirm there is no checked out data?](https://www.ssw.com.au/rules/do-you-confirm-there-is-no-checked-out-data/).
> 2. Reply to this email with something like: ‘Done - x files checked in’
> 
> Note: See all files you have checked out at [About SSW.Dory](https://sswcom.sharepoint.com/SitePages/SSW.Dory.aspx) (This list is automatically refreshed each day).
> 
> Image 
> -- Powered by Power Automate, Job: [SSW.Dory.Emailing](https://make.powerautomate.com/environments/473d2654-2185-46f6-9b9a-167b8d93c807/flows/ce4a3532-f868-4240-44a4-10266788fcfb/details)

to


> From: SSW.Dory [SSW]
> Sent: Wednesday, 23 August 2023 8:01 AM
> To: Levi Jackson [SSW] <[LeviJackson@ssw.com.au](mailto:LeviJackson@ssw.com.au)>
> Cc: SSWDoryEmails <[SSWDoryEmails@ssw.com.au](mailto:SSWDoryEmails@ssw.com.au)>
> Subject: SSW.Dory | 📂 SharePoint files need your attention | Levi Jackson [SSW] 
>  
> (This product is currently in BETA, we'd love your [feedback](https://github.com/SSWConsulting/SSW.Dory/issues) 😉)
> 
> ### Hi Levi,
> You currently have [checked out files in SharePoint](https://sswcom.sharepoint.com/SitePages/SSW.Dory.aspx) (list refreshed daily):
> 
> * [https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-09.aspx](https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-09.aspx)
> * [https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-11.aspx](https://sswcom.sharepoint.com/SitePages/The-SSW-Times-2022-11.aspx)
> 
> 1. If you are no longer editing these files, check them in! 
> 2. Reply to this email with 'Done - X files checked in’
> 
> \< As per [Do you confirm there is no checked out data?](https://www.ssw.com.au/rules/do-you-confirm-there-is-no-checked-out-data/) \>
> 
> Image 
> -- Powered by Power Automate, Job: [SSW.Dory.Emailing](https://make.powerautomate.com/environments/473d2654-2185-46f6-9b9a-167b8d93c807/flows/ce4a3532-f868-4240-44a4-10266788fcfb/details)

**Comment by tiagov8** [comment]
BTW - I would love to NOT have the task 2 "Reply done X files checked in"... 

This extra step takes away all of the beauty of automation, making this seem bureaucratic (who am I sending this to? Is someone manually checking these? isn't the goal to just keep things going?)

(I suspect that is probably never gonna be approved by Adam 😬)

Maybe I'd be happy with replacing it with _"Note: Please reply to this email is you have any reason to not check in your files"_ so in this case it's useful for following up

**Comment by Jord-Gui** [comment]
Done

![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/b233a23c-a2b3-4218-b054-7de0dbff2989)\
Figure: Updated Sharepoint email



![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/8d868bea-1561-47cb-bc27-e2f46a3a819b)\
Figure: Updated GitHub email

**Comment by tiagov8** [comment]
Hi @Jord-Gui 

1. **Consistency** - We should fix the inconsistency on the rule link between the 2 emails (I assume we won't be sending separated emails for GitHub review VS GitHub follow up...)

   On GitHub email, 
   Please change from:

> You should get a PR merged as soon as possible, as per rule [SSW.Rules | Pull Request - Do you do over the shoulder reviews?](https://www.ssw.com.au/rules/over-the-shoulder-prs).

to

> \< As per [Pull Request - Do you do over the shoulder reviews?](https://www.ssw.com.au/rules/over-the-shoulder-prs) \>


2. **Consistency** - On GitHub email, move the sentence above to come after the numbered task

3. **Clarity** - On GitHub email, please change from: 
> You currently have the following PRs open in GitHub to action/review:

to

> You currently have GitHub Pull Requests to review or follow up with others (list refreshed daily):

4. **Consistency** - On GitHub email, add a new task 1: 

> "1. Please try and get the **PRs merged** 

5. **UX** - On both emails, please change the "Note" from

> Note: Contact the SSW.Dory team at [SSW.Dory Team](https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&forceUCI=1&pagetype=entityrecord&etn=ssw_responsibility&id=22bcddf6-4942-ee11-bdf4-6045bd3df09b).

 to

> [Contact the SSW.Dory team](https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&forceUCI=1&pagetype=entityrecord&etn=ssw_responsibility&id=22bcddf6-4942-ee11-bdf4-6045bd3df09b).

6. **UX** - Move the sentence above to come right after the "Job:"

> _-- Powered by Power Automate, Job: [SSW.Dory.Emailing](https://make.powerautomate.com/environments/473d2654-2185-46f6-9b9a-167b8d93c807/flows/ce4a3532-f868-4240-44a4-10266788fcfb/details) | Contact the SSW.Dory team](https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&forceUCI=1&pagetype=entityrecord&etn=ssw_responsibility&id=22bcddf6-4942-ee11-bdf4-6045bd3df09b)_

7. **UX** - I found the link to contact the team quite unfriendly... Could we point users to GitHub Issues or Dicussions instead?
  
  <img width="1666" alt="Screenshot 2023-08-29 at 9 05 18 AM" src="https://github.com/SSWConsulting/SSW.Dory/assets/12601228/68986d4e-1aef-42f3-b6b5-3c78a86408a5">
  
  **❌ Figure: I wouldn't expect to see this from a contact link...**

8. **UI** - Please update both logo images with the below (size 64x64px and dark/light mode safe)

![sharepoint-logo](https://github.com/SSWConsulting/SSW.Dory/assets/12601228/997e0c44-c4d3-4c72-8b03-ca572b54a920)

![github-logo](https://github.com/SSWConsulting/SSW.Dory/assets/12601228/8ab413f9-0ded-40bc-94c6-0b1f664c89cb)

**Comment by Jord-Gui** [comment]
Done

![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/6dba0788-0faf-490b-b988-9cb672af97ed)

Figure: Updated GitHub email


![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/c629b730-7605-4787-9d84-bdc513e6e0fe)

Figure: Updated SharePoint email

**Comment by tiagov8** [comment]
Hi @Jord-Gui 

Looking great, but sorry... I have a few more things:

1. I think the exclamation mark ❗️ makes the email less friendly... the bold is enough for emphasis. Can we ditch "!" from both emails?
2. Can you make alll "x" representing a number in Uppercase "X"
3. On the SharePoint one, I would break a line before 'Done - X files..."
4. Did you talk to the PO/Team about my task 7 on https://github.com/SSWConsulting/SSW.Dory/issues/38#issuecomment-1697772035 ?

**Comment by Jord-Gui** [comment]
Hi @tiagov8 

        > 4. Did you talk to the PO/Team about my task 7 on https://github.com/SSWConsulting/SSW.Dory/issues/38#issuecomment-1697772035 ?

I've changed the contact URL to https://github.com/SSWConsulting/SSW.Dory/discussions 😁

**Comment by Jord-Gui** [comment]
Done

<img width="616" alt="image" src="https://github.com/SSWConsulting/SSW.Dory/assets/41951199/a6bb6830-5760-4cc7-94e6-c41487dd2f50"> \
Figure: Updated SharePoint email

<img width="616" alt="image" src="https://github.com/SSWConsulting/SSW.Dory/assets/41951199/a38cb860-1705-4f3f-91ba-df471521a6f1"> \
Figure: Updated GitHub email
