### ISSUE TITLE
♻️ Changes to SSW.Dory Website Content

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#48]
```[tasklist]
### Tasks
- [x] Change GitHub screenshot to light mode
- [x] Change tagline as it doesn't mean anything
- [x] Move the screenshot of reminder emails to the top of the screen as that is what end users mainly focus on. This is the end product (add header). The next ones become 'How it works' screenshots.
- [x] Add context to outlook email screenshot so it is clear that it is an email. Also add the one for SharePoint
- [x] Add paragraphs to describe the screenshots. What are the parameters e.g. is the PR open for more than a day/week? When does it consider it in need of a reminder - mention how often the emails are sent e.g. every morning. Feel free to test please from Tiago
- [x] Get test pass on content from Tiago
```

**Comment by Jord-Gui** [comment]
✅ Done - Test Pass as per conversation with @tiagov8 

![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/fdca25ee-0210-4c2e-8585-48f2a8338072)

**Figure: SSW Dory [website](https://www.sswdory.com/)**
