### ISSUE TITLE
Migrate to production environment

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#6]
Can contact Chris Schultz for help as he's done this
```[tasklist]
### Tasks
- [x] Change over plugins from personal ones to the Dory service account
- [x] Set up notifications to notify e.g. Sharepoint/System Admins when a flow fails
- [x] Set ticket owners back to their original owners instead of the Dory service account used for testing
- [x] Move Open Ticket List to SSW Dory V2 in sharepoint from SSW Dory Dev
```
