### ISSUE TITLE
♻️ Refactor Landing-Page Website Architecture

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#63]
Cc: @bradystroud @adamcogan @JackDevAU @leahy268 

### Pain
The SSW.Dory landing-page website currently uses a Jekyll template hosted in GitHub Pages, which was a quick way to get content up but is too restrictive. We want to update the website to have a custom design. 

### Potential solutions

1. WordPress (may not be worth the cost for a project site)
2. Gatsby + GitHub Pages (Gatsby not SSW recommended solution, but has documentation on how to deploy to GitHub Pages)
3. NextJS (more work involved to get it deployed and may be overkill for this. Wouldn't be an issue if we hosted on Vercel)

As this is a complete re-architect, we can also trial out Bun 1.0 https://bun.sh/blog/bun-v1.0
```[tasklist]
### Tasks
- [x] Confirm cost of hosting on WordPress
- [x] Write down Pros and Cons on Gatsby and NextJS
- [x] Get solution approved by Product Owner
```

**Comment by Jord-Gui** [comment]
Wordpress has limited sites. Around 6K a year for 10 sites. We already have 27. Initial discussion was that it's not worth taking up the remaining 3 sites for a single page website.

**Comment by JackDevAU** [comment]
Maybe try out Astro 👀https://astro.build/

**Comment by Jord-Gui** [comment]
https://www.ssw.com.au/rules/best-static-site-tech-stack/

**Comment by Jord-Gui** [comment]
Summary

1. WordPress
    - ✅ Easiest to implement
    - ❌ Pricey
    - ❌ Limited sites, ~$6k a year for 10 sites
    - ❌ We already have 27 sites used, leaving 3 more slots available
    - ❌ Initial discussion - not worth for a static single page website.
2. NextJS
    - ✅ Popular
    - ✅ SSW recommended
    - ❌ Overkill for a static single page website
    - ❌ No native support/more work involved to deploy to GitHub Pages or Azure static web apps
3. Gatsby
    - ✅ Good for static sites
    - ✅ Documentation on how to deploy to GitHub Pages or Azure static web apps
    - ❌ Not as popular as NextJS
4. Astro
    - ✅ Target towards content-first websites
    - ✅ Faster than NextJS and Gatsby for this use case
    - ✅ Documentation to deploy to GitHub Pages or Azure static web apps
    - ❌ Not as popular as NextJS or Gatsby

**Comment by Jord-Gui** [comment]
Done - as per discussion, will refactor to NextJS. This is tracked in Issue #64
