### ISSUE TITLE
♻️ Move Landing-Page to NextJS

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#64]
```[tasklist]
### Tasks
- [x] Copy Code Auditor (https://codeauditor.com/) design using NextJS
- [x] Deploy to Azure Storage (https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website)
- [x] Create GitHub Action that auto deploys to blob storage on push to main
- [x] Move url over to Azure Storage site
- [x] Add CDN (Frontdoor)
```

**Comment by Jord-Gui** [comment]
As per conversation with @christoment and @christianmorfordwaitessw, better to deploy to Azure static storage as opposed to Azure static web apps as:
- ❌ Static web apps uses my GitHub account to link to the Dory GitHub repo and it'll break if I leave
- ❌ Static web apps involves some 'clickops' to set up
- ✅ Static storage can be set up using bicep/yaml file (infrastructure as code)

**Comment by Jord-Gui** [comment]
As per conversation with @bradystroud, no need for adding in a CMS at this stage as it is very low value.

**Comment by Jord-Gui** [comment]
✅ Done - website has been moved to NextJS and hosted on Azure Storage.

![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/30f7de79-4275-4435-a5e2-f5f299bdc0f9)

**Figure: New website design**
