### ISSUE TITLE
Complete SSW.Dory.GitHub flow

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#9]
```[tasklist]
### Tasks
- [x] Change to use GitHub connector as opposed to API to list PRS
- [x] Test on SSW.People & SSW.Rules repo
- [x] Set time of expiry as an environment variable
```
